 
# create a docker-compose.yml file
version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.8
    ports:
      - '27017:27017'
